config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: {
  sessions: 'users/sessions' ,
  registrations: 'users/registrations',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get "users/sign_up/registration", to: "users/registrations#sns", as: "new_user_signup_registration"
    get "users/sign_up/sms_confirmation", to: "users/registrations#phone", as: "new_user_signup_sms_confirmation"
    get "users/sign_up/address_confirmation", to: "users/registrations#address", as: "new_user_signup_address_confirmation"
    get "users/sign_up/credit_confirmation", to: "users/registrations#credit", as: "new_user_signup_credit_confirmation"
  end

  root "items#index"
  resources :items, only: [:new, :create] do
    member do

    end
  end
  resources :user_profiles, only: [:edit,:update]
  resources :users, only: [:index]
  resources :items do
    collection do
      get :category
      get :search
      post 'pay/:id' => 'items#pay', as: 'pay'
    end
    member do
      get :buy
      get :sold
    end
  end

  resources :addresses

  resources :item_images, only: [:destroy]

  resources :item_images, only: [:update, :destroy]

  resources :categories, only: [:show]
  resources :brands, only: [:show]
  resources :users  do
    collection do
      get :logout
      get :card
      get :phone
    end
  end
  resources :users, only: [:create] do
    resources :items, only: [:show] do
      collection do
        get :onsale
        get :orderd
        get :sold
      end
    end
  end
  resources :items do
    resources :comments, only: [:create]
  end
  resources :comments
end

app/views/modules/_mypage-side-navi.html.haml
.left-content__bar
  %nav.mypage-navigation
    %ul.mypage-nav__list
      %li#first__list
        = link_to users_path, class: "mypage-nav__list__item" do
          マイページ
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          お知らせ
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          やることリスト
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          いいね！一覧
          %i.fa.fa-chevron-right
      %li
        = link_to  new_item_path, class: "mypage-nav__list__item" do
          出品する
          %i.fa.fa-chevron-right
      %li
        = link_to onsale_user_items_path(current_user), class: "mypage-nav__list__item" do
          出品した商品-出品中
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          出品した商品-取引中
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          出品した商品-売却済み
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          購入した商品-取引中
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          購入した商品-過去の取引
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          ニュース一覧
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          評価一覧
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          ガイド
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          お問い合わせ
          %i.fa.fa-chevron-right
  .left-content__bar
    %h4.mypage-nav__head メルペイ
    %ul.mypage-nav__list
      %li#first__list
        = link_to "", class: "mypage-nav__list__item" do
          売上・振込申請
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          ポイント
          %i.fa.fa-chevron-right
  .left-content__bar
    %h4.mypage-nav__head 設定
    %ul.mypage-nav__list
      %li#first__list
        = link_to edit_user_profile_path(current_user), class: "mypage-nav__list__item" do
          プロフィール
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          発送元・お届け先住所変更
          %i.fa.fa-chevron-right
      %li
        = link_to  card_users_path, class: "mypage-nav__list__item" do
          支払い方法
          %i.fa.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav__list__item" do
          メール/パスワード
          %i.fa.fa-chevron-right
      %li
        = link_to edit_address_path(current_user), class: "mypage-nav__list__item" do
          本人情報
          %i.fa.fa-chevron-right
      %li
        = link_to phone_users_path, class: "mypage-nav__list__item" do
          電話番号の確認
          %i.fa.fa-chevron-right
      %li
        = link_to logout_users_path, class: "mypage-nav__list__item" do
          ログアウト
          %i.fa.fa-chevron-right

app/views/modules/_mypage-top.html.haml
.mypage
  %main.mypage__body.clearfix

    .mypage__body__main
      %section.mypage__user-icon
        = link_to "#" do
          %figure
            = image_tag "no-translate-detected_318-10541.jpg", alt: "ユーザーアイコン", alt: "ユーザーアイコン", height: "60", width: "60"
          %h2
            ユーザー名
          .mypage__number
            %p
              評価
              %span 0
            %p.right
              出品数
              %span 0

      %section.mypage__tab
        %ul.mypage__tab__list
          %li.notification
            %h3
              = link_to "#" do
                お知らせ
          %li.todo
            %h3
              = link_to "#" do
                やることリスト
        .mypage__tab-content
          %ul.notification-list
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", alt: "メルカリロゴ"
                .notification-list__body
                  .notification-list__body__text【7日間限定】10人に1人最大P6,000もらえるキャンペーン開始
                  %time
                    %i.fas.fa-clock-o
                    %span 19 時間前
                %i.fas.fa-angle-right
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", alt: "メルカリロゴ"
                .notification-list__body
                  .notification-list__body__text 事務局から個別メッセージ「ログイン通知」
                  %time
                    %i.fas.fa-clock-o
                    %span 1 日前
                %i.fas.fa-angle-right
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", alt: "メルカリロゴ"
                .notification-list__body
                  .notification-list__body__text 事務局から個別メッセージ「ログイン通知」
                  %time
                    %i.fas.fa-clock-o
                    %span 1 日前
                %i.fas.fa-angle-right
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", alt: "メルカリロゴ"
                .notification-list__body
                  .notification-list__body__text 事務局から個別メッセージ「【重要】新サービス開始に伴う利用規約改訂のお知らせ」
                  %time
                    %i.fas.fa-clock-o
                    %span 16 日前
                %i.fas.fa-angle-right
            %li
              = link_to "#", class: "notification-list__link" do
                %figure
                  = image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", alt: "メルカリロゴ"
                .notification-list__body
                  .notification-list__body__text 【あと3日】対象カテゴリーが売れたら“必ず“ポイントがもらえるキャンペーン開催中
                  %time
                    %i.fas.fa-clock-o
                    %span 21 日前
                %i.fas.fa-angle-right
            %li.notification-list__all
              = link_to "#" do
                一覧を見る

      %section.mypage__trading-traded
        %h2.mypage-tab-head 購入した商品
        %ul.mypage-tabs
          %li.trading
            %h3
              = link_to "#" do
                取引中
          %li.traded
            %h3
              = link_to "#" do
                過去の取引
        .tab-content
          .traded-list
            %figure
              = image_tag "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", alt: "メルカリロゴ"
            .traded-list__not-found 取引中の商品がありません