config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: {
  sessions: 'users/sessions' ,
  registrations: 'users/registrations',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get "users/sign_up/registration", to: "users/registrations#sns", as: "new_user_signup_registration"
    get "users/sign_up/sms_confirmation", to: "users/registrations#phone", as: "new_user_signup_sms_confirmation"
    get "users/sign_up/address_confirmation", to: "users/registrations#address", as: "new_user_signup_address_confirmation"
    get "users/sign_up/credit_confirmation", to: "users/registrations#credit", as: "new_user_signup_credit_confirmation"
  end

  root "items#index"
  resources :items, only: [:new, :create] do
    member do

    end
  end
  resources :user_profiles, only: [:edit,:update]
  resources :users, only: [:index]
  resources :items do
    collection do
      get :category
      get :search
      post 'pay/:id' => 'items#pay', as: 'pay'
    end
    member do
      get :buy
      get :sold
    end
  end

  resources :addresses

  resources :item_images, only: [:destroy]

  resources :item_images, only: [:update, :destroy]

  resources :categories, only: [:show]
  resources :brands, only: [:show]
  resources :users  do
    collection do
      get :logout
      get :card
      get :phone
    end
  end
  resources :users, only: [:create] do
    resources :items, only: [:show] do
      collection do
        get :onsale
        get :orderd
        get :sold
      end
    end
  end
  resources :items do
    resources :comments, only: [:create]
  end
  resources :comments
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  enum condition: {"新品、未使用": 1, "未使用に近い": 2, "目立った傷や汚れなし": 3, "やや傷や汚れあり": 4, "傷や汚れあり": 5, "全体的に状態が悪い": 6}
  enum days_to_ship: {"1~2日で発送": 1, "2~3日で発送": 2, "4~7日で発送": 3}
  enum shipping_fee: {"着払い(購入者負担)": false, "送料込み(出品者負担)": true}

  belongs_to_active_hash :prefecture
  belongs_to :user
  belongs_to :category
  has_one :order_status, dependent: :destroy
  belongs_to :brand, optional: true
  has_many :item_images, dependent: :destroy
  has_many :comments
  accepts_nested_attributes_for :item_images

  validates :name, presence: true
  validates :comment, presence: true
  validates :shipping_fee, presence: true
  validates :days_to_ship, presence: true
  validates :condition, presence: true
  validates :price, presence: true, numericality: { greater_than: 300, less_than: 9999999 }

  validates :item_images, length: { minimum: 1, maximum: 10}

  scope :by_category_id, -> (id) {eager_load(category: :parent).where("category_id = ? or categories.parent_id = ? or parents_categories.parent_id = ?", id, id, id)}

  def self.ransackable_scopes(auth_object = nil)
    %i[by_category_id]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :pay, :buy, :sold]
  before_action :current_user_not_buy, only: [:buy]
  before_action :buy_not_sold, only: [:sold]
  before_action :buy_sold, only: [:buy]


  def index
    @ladies = Item.ransack(by_category_id: 1.0).result.order(created_at: "DESC").limit(4)
    @mens = Item.ransack(by_category_id: 2).result.order(created_at: "DESC").limit(4)
    @kids = Item.ransack(by_category_id: 3).result.order(created_at: "DESC").limit(4)
    @janel = Item.ransack(brand_id_eq: 1).result.order(created_at: "DESC").limit(4)
    @biton = Item.ransack(brand_id_eq: 3).result.order(created_at: "DESC").limit(4)
    @shrimp = Item.ransack(brand_id_eq: 4).result.order(created_at: "DESC").limit(4)
    @mike = Item.ransack(brand_id_eq: 2).result.order(created_at: "DESC").limit(4)
  end

  def show
    @item = Item.find(params[:id])
    @categories = Category.ransack(parent_id_null: true).result
    @janel = Item.ransack(brand_id_eq: 1).result.limit(3)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def new
    @item = Item.new
    @item.item_images.build
    @categories = Category.ransack(parent_id_null: true).result
  end

  def create
    @item = Item.new(item_params)
    @categories = Category.ransack(parent_id_null: true).result
    if @item.save
      respond_to do |format|
        format.html
        format.json {render json: @item}
      end
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @categories = Category.ransack(parent_id_null: true).result
  end


  def pay
    item = Item.find(params[:id])
      Payjp.api_key = 'sk_test_c28ae49cafa2c8609f211aea'
      charge = Payjp::Charge.create(
      amount: item.price,
      card: params['payjp-token'],
      currency: 'jpy')
    item.sales_condition = true
    item.save

    status = OrderStatus.create(purchaser_id: current_user.id, seller_id: item.user.id, item_id: item.id)

    if charge.present?
      redirect_to "/items/#{item.id}/sold"
    else
      redirect_to  "/items/#{item.id}"
    end
  end



  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      respond_to do |format|
        format.html
        format.json {render json: @item}
      end
    else
      render :edit
    end
  end

  def category
    @categories = Category.ransack(parent_id_eq: params[:id]).result

    respond_to do |format|
      format.html
      format.json {render json: @categories.select(:id, :name)}
    end
  end


  def destroy
    item = Item.find(params[:id])
    if item.user_id == current_user.id
      item.destroy
      redirect_to onsale_user_items_path(current_user), flash: {success: '商品を削除しました'}
    end
  end

  def search
    @items = Item.ransack(name_cont: params[:keyword]).result
  end

  def onsale
    @items = Item.ransack(user_id_eq: current_user.id)
  end

  def buy
    @item = Item.find(params[:id])
  end

  def sold
    @item = Item.find(params[:id])
    # @user = User.find(params[:id])
  end




  private

  def buy_not_sold
    item = Item.find(params[:id])
    unless item.sales_condition
      redirect_to "/items/#{item.id}/buy"
    end
  end

  def buy_sold
    item = Item.find(params[:id])
    if item.sales_condition == true
      redirect_to "/items/#{item.id}/sold"
    end
  end

  def current_user_not_buy
    item = Item.find(params[:id])
    if current_user.id == item.user.id
      redirect_to "/items/#{item.id}"
    end
  end

  def item_params
    params.require(:item).permit(:name, :comment, :category_id, :brand_id, :shipping_fee, :prefecture_id, :days_to_ship, :price, :condition, item_images_attributes: [:image]).merge(user_id: current_user.id)
  end


end

app/views/items/_brand-menu.html.haml
%ul.brand-menu
  - Brand.all.each do |brand|
    %li
      = link_to brand.name, brand_path(brand)

app/views/items/_carousel.html.haml
.carousel
  .carousel__first
    = link_to image_tag("banner-new-life.jpg"), "#"
  .carousel__second
    = link_to image_tag("main-index.png"), "#"
  .carousel__third
    = link_to image_tag("banner-new-register.jpg"), "#"

app/views/items/_category-menu.html.haml
%ul.category-menu__level1
  -categories = Category.all.eager_load(children: :children)
  - categories.all.each do |category1|
    - unless category1.parent_id
      %li
        = link_to category1.name, category_path(category1)
        %ul.category-menu__level1__level2
          - category1.children.each do |category2|
            %li
              = link_to category2.name, category_path(category2)
              %ul.category-menu__level1__level2__level3
                - category2.children.each do |category3|
                  %li
                    =link_to category3.name, category_path(category3)

app/views/items/_item.html.haml
.item-box
  = link_to item_path(item), class: "item-menu-top" do
    = image_tag item.item_images[0].image.url, class: "item-box__image" 
    - unless item.sales_condition
      .none-sold
    - else
      .item-tag-sold-out-top-page
        .sold-out-text-top-page SOLD
    .item-box__body
      %h4.item-box__body__name #{item.name}
      .item-box__body__price
        %h5 ¥ #{item.price}
        %p （税込）
        
  

app/views/items/_thumbnail.html.haml
.upload-item{:id => "uploadItem-\#{index}"}>
  .upload-item__container
    %figures
      %img.upload-item__container__image{:id => "uploadImage-\#{index}", :src => "\#{image}"}/
      %img.upload-item__container__cropped-image{id: "uploadCroppedImage-#{index}"}
    .upload-item__container__button{id: "upButton-#{index}"}
      %a.upload-item__container__button__edit{"data-id" => "\#{index}"} 編集
      %a.upload-item__container__button__delete{"data-id" => "\#{index}"} 削除
`

app/views/items/buy.html.haml
= render "layouts/single-header"
.items__buy_cf__container
  .items__buy_cf__container__main
    %h2.items__buy_cf__container__main__header
      購入を確定しますか?
    .items__buy_cf__container__main__content
      .items__buy_cf__container__main__content__inner
        .items__buy_cf__container__main__content__inner__item_image_container
          = image_tag @item.item_images[0].image.url, class: "item_photo"
        %p.items__buy_cf__container__main__content__inner__item_name
          = @item.name
          %p.items__buy_cf__container__main__content__inner__buy_form__item_price
            = "¥ " + "#{@item.price}"
            %span.items__buy_cf__container__main__content__inner__buy_form__item_price__shipping_fee
              - if @item.shipping_fee=="送料込み(出品者負担)"
                送料込み
              - else
                着払い
            .items__buy_cf__container__main__content__inner__buy_form__accordion
              .items__buy_cf__container__main__content__inner__buy_form__accordion_toggle
                ポイントはありません
            .payment
              .payment_text
                支払い金額
              .payment_price
                = '¥ ' + "#{@item.price}"
      .payment_form
        = form_tag(action: :pay, method: :post) do
          %script.payjp-button{src: "https://checkout.pay.jp", type: "text/javascript" ,"data-text" => "購入する" ,"data-key" => "pk_test_33d180c3147e00a55623bdf4", }

    .buy_user_info
      .buy_user_info_container
        %h3
          配送先
        %address
          .buy_user_info_container_text
            = "〒#{current_user.address.postal_code}"
            %br
            = "#{current_user.address.prefecture.name} #{current_user.address.city} #{current_user.address.block} #{current_user.address.building}"
        .buy_user_info_container__angle_right
          =link_to "#", class: "angle-right" do
            変更する
            %i.fab-fa-angle-right
    .buy_user_info
      .buy_user_info_container
        %h3
          支払い方法
        .buy_user_info_container_text
          ************4242
          %br
          11 / 22
        .buy_user_info_container_visa
          = image_tag "https://i1.wp.com/creditcard-site.com/images/visa_shin_logo2.png?w=1170&ssl=1", size: "49x15", alt: "写真"
        .buy_user_info_container__angle_right
          =link_to "#", class: "angle-right" do
            変更する
            %i.fab.fa-sangle-right
= render "layouts/single-footer"
= render "layouts/sell-button"

app/views/items/edit.html.haml
.container.new-item
  .new-item__header
    .single-header
      = link_to image_tag("logo.svg"), "/"
  .new-item__main
    .new-item__main__container
      .new-item__main__container__head
        %h2 商品の情報を入力
      = form_with model: @item, local: true , id: "itemForm", class: "new-item__main__container__form sell-form" do |f|
        .sell-form__image{"data-image_count": @item.item_images.count}
          %h3
            出品画像
            %span 必須
          %p 最大10枚までアップロードできます
          = f.fields_for @item.item_images do |ff|
            = ff.file_field :image , class: "sell-form__image__input", accept: ".jpg, .jpeg, .png", multiple: true
            .sell-form__image__dropbox#uploadField
              .sell-form__image__dropbox__thumbnail#thumbnailBox
              = render @item.item_images
              .sell-form__image__dropbox__wrapper.dropbox-wrapper
                - if @item.item_images.length == 10
                  .sell-form__image__dropbox__wrapper__inner#dropbox{style: "display:none"}
                    %pre
                      ドラッグアンドドロップ
                      またはクリックしてファイルをアップロード
                - else
                  .sell-form__image__dropbox__wrapper__inner#dropbox
                    %pre
                      ドラッグアンドドロップ
                      またはクリックしてファイルをアップロード
            .sell-form__image__error
        .sell-form__summary
          .sell-form__summary__name
            %h5
              商品名
              %span 必須
            = f.text_field :name, class: "sell-form__summary__name", id: "nameField", placeholder: "商品名（必須 40文字まで)"
            .sell-form__summary__name__error
          .sell-form__summary__comment
            %h5.mt-40
              商品の説明
              %span 必須
            = f.text_area :comment, class: "sell-form__summary__comment", id: "commentField", rows: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
            .sell-form__summary__comment__error
        .sell-form__detail
          %h6 商品の詳細
          .sell-form__detail__select-box
            .sell-form__detail__select-box__category
              %h5
                カテゴリー
                %span 必須
              - if !@item.category.parent
                .sell-form__detail__select-box__wrap
                  = f.select :category_id, @categories.map{|t| [t.name, t.id]}, prompt: "---", selected: @item.category_id
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__wrap#sell-form-sub_category
                  = f.select :sub_category_id, @item.category.children.map{|t| [t.name, t.id]}, prompt: "---"
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__wrap#sell-form-sub_sub_category{style: "display:none"}
                  %select#item_sub_sub_category_id{name: ""}
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__category__error
              - elsif !@item.category.parent.parent
                .sell-form__detail__select-box__wrap
                  = f.select :category_id, @categories.map{|t| [t.name, t.id]}, prompt: "---", selected: @item.category.parent.id
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__wrap#sell-form-sub_category
                  = f.select :sub_category_id, @item.category.parent.children.map{|t| [t.name, t.id]}, prompt: "---", selected: @item.category_id
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__wrap#sell-form-sub_sub_category
                  = f.select :sub_sub_category_id, @item.category.children.map{|t| [t.name, t.id]}, prompt: "---"
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__category__error
              - elsif !@item.category.parent.parent.parent
                .sell-form__detail__select-box__wrap
                  = f.select :category_id, @categories.map{|t| [t.name, t.id]}, prompt: "---", selected: @item.category.parent.parent.id
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__wrap#sell-form-sub_category
                  = f.select :sub_category_id, @item.category.parent.parent.children.map{|t| [t.name, t.id]}, prompt: "---", selected: @item.category.parent.id
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__wrap#sell-form-sub_sub_category
                  = f.select :sub_sub_category_id, @item.category.parent.children.map{|t| [t.name, t.id]}, prompt: "---", selected: @item.category_id
                  %i.fas.fa-angle-down
                .sell-form__detail__select-box__category__error
              - else
            #sell-form-brand
              %h5.mt-40
                ブランド
                %span.gray 任意
              .sell-form__detail__select-box__wrap
                = f.select :brand_id, Brand.all.map{|t| [t.name, t.id]}, prompt: "---"
                %i.fas.fa-angle-down
            .sell-form__detail__select-box__condition
              %h5.mt-40
                商品の状態
                %span 必須
              .sell-form__detail__select-box__wrap
                = f.select :condition, Item.conditions.keys, prompt: "---"
                %i.fas.fa-angle-down
              .sell-form__detail__select-box__condition__error
        .sell-form__shipping
          %h6
            配送について
            = link_to "?", "/", class: "question"
          .sell-form__shipping__select-box
            .sell-form__shipping__select-box__fee
              %h5
                配送料の負担
                %span 必須
              .sell-form__shipping__select-box__wrap
                = f.select :shipping_fee, Item.shipping_fees.keys, prompt: "---"
                %i.fas.fa-angle-down
              .sell-form__shipping__select-box__fee__error
            .sell-form__shipping__select-box__region
              %h5.mt-40
                発送元の地域
                %span 必須
              .sell-form__shipping__select-box__wrap
                = f.select :prefecture_id, Prefecture.all.map{|t| [t.name, t.id]}, prompt: "---"
                %i.fas.fa-angle-down
              .sell-form__shipping__select-box__region__error
            .sell-form__shipping__select-box__days
              %h5.mt-40
                発送までの日数
                %span 必須
              .sell-form__shipping__select-box__wrap
                = f.select :days_to_ship, Item.days_to_ships.keys, prompt: "---"
                %i.fas.fa-angle-down
              .sell-form__shipping__select-box__days__error
        .sell-form__price
          %h6
            販売価格(300〜9,999,999)
            = link_to "?", "/", class: "question"
          .sell-form__price__select-box
            .sell-form__price__select-box__price-wrap
              .sell-form__price__select-box__price-wrap__input
                .sell-form__price__select-box__price-wrap__input__left
                  %h5
                    価格
                    %span 必須
                .sell-form__price__select-box__price-wrap__input__right
                  %p ¥
                  = f.text_field :price, id: "priceField", placeholder: "例）300"
              .sell-form__price__select-box__price-wrap__error
            .sell-form__price__select-box__charge-wrap
              .sell-form__price__select-box__charge-wrap__left
                %p 販売手数料(10%)
              .sell-form__price__select-box__charge-wrap__right
                %p#chargeField -
            .sell-form__price__select-box__profit-wrap
              .sell-form__price__select-box__profit-wrap__left
                %h3 販売利益
              .sell-form__price__select-box__profit-wrap__right
                %h3#profitField -
        .sell-form__submit
          %p 禁止されている出品、行為を必ずご確認ください。
          %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
          %p また、出品をもちまして加盟店規約に同意したことになります。
          .sell-form__submit__button
            = image_tag "icon_loader.gif", class: "sell-form__submit__button__load", id: "loadIcon"
            = f.submit "変更する", id: "newItemSubmitButton", class: "btn btn-large", type: "button"
          = link_to "もどる", "/", class: "sell-form__submit__back btn btn-gray "
= render "layouts/single-footer"
= render "layouts/cropping-modal"

app/views/items/index.html.haml
- content_for :head do
  %meta{name: "turbolinks-cache-control", content: "no-cache"}
.container
  = render "layouts/header"
  = render "carousel"
  .main
    %h2 ピックアップカテゴリー
    .pickup-box
      %h3
        = link_to "レディース新着アイテム", category_path(1)
      .pickup-box__items
        = render @ladies
    .pickup-box
      %h3
        = link_to "メンズ新着アイテム", category_path(2)
      .pickup-box__items
        = render @mens
    .pickup-box
      %h3
        = link_to "ベビー・キッズ新着アイテム", category_path(3)
      .pickup-box__items
        = render @kids
    %h2 ピックアップブランド
    .pickup-box
      %h3
        = link_to "ジャネル新着アイテム"
      .pickup-box__items
        = render @janel
    .pickup-box
      %h3
        = link_to "ルイビトン新着アイテム"
      .pickup-box__items
        = render @biton
    .pickup-box
      %h3
        = link_to "シュリンプ新着アイテム"
      .pickup-box__items
        = render @shrimp
    .pickup-box
      %h3
        = link_to "マイキ新着アイテム"
      .pickup-box__items
        = render @mike
  = render "layouts/aside"
  = render "layouts/footer"
  = render "layouts/sell-button"

app/views/items/onsale.html.haml
- breadcrumb :onsale

= render "layouts/header"

%main.l-container
  .l-container__mypage
    = render "modules/mypage-side-navi"
    %h1 工事中

= render "layouts/aside"
= render "layouts/footer"
= render "layouts/sell-button"

app/views/items/search.html.haml
= render "layouts/header"
.search
  .search__container
    %h1 検索結果 1- #{@items.count}件
    .search__container__item
      = render @items
= render "layouts/aside"
= render "layouts/footer"
= render "layouts/sell-button"

app/views/items/show.html.haml
- content_for :head do
  %meta{name: "turbolinks-cache-control", content: "no-cache"}
.container
  = render "layouts/header"
  .main-background
    %section.item-box-container
      %h1
        .item-name
          = @item.name
      .item-main-content
        .item-photo
          .slider
            - @item.item_images.each do |item_image|
              .slider__item
                = image_tag item_image.image.url
                - unless @item.sales_condition
                  .none-sold
                - else
                  .item-tag-sold-out-top
                    .sold-out-text-top SOLD

          .thumbnail
            - @item.item_images.each.with_index do |item_image, index|
              - if index == 0
                .thumbnail__item.current{"data-index": index}
                  .thumbnail__item__box
                    = image_tag item_image.image.url
              - else
                .thumbnail__item{"data-index": index}
                  .thumbnail__item__box
                    = image_tag item_image.image.url
            - if @item.item_images.length > 5
              - for i in 1..(10 - @item.item_images.length)
                .thumbnail__dummy
        %table.item-detail-table
          %tbody
            %tr
              %th 出品者
              %td
                = link_to "#{@item.user.user_profile.nickname}", "/", class: "user-name-string";
                .item-user-ratings
                  .item-user-rating
                    %i.fas.fa-laugh
                    %span 0
                  .item-user-rating
                    %i.fas.fa-meh
                    %span 0
                  .item-user-rating
                    %i.fas.fa-frown
                    %span 0
            %tr
              %th カテゴリー
              %td
                - if !@item.category.parent_id
                  = link_to "/" do
                    .item-detail-table-sub
                      = @item.category.name
                - elsif !@item.category.parent.parent_id
                  = link_to "/" do
                    .item-detail-table-sub
                      = @item.category.parent.name
                  = link_to "/" do
                    .item-detail-table-sub__sub
                      %i.fas.fa-angle-right
                      = @item.category.name
                - else
                  = link_to "/" do
                    .item-detail-table-sub
                      = @item.category.parent.parent.name
                  = link_to "/" do
                    .item-detail-table-sub__sub
                      %i.fas.fa-angle-right
                      = @item.category.parent.name
                  = link_to "/" do
                    .item-detail-table-sub__sub__sub
                      %i.fas.fa-angle-right
                      = @item.category.name
            %tr
              %th ブランド
              %td
                = link_to "/" do
                  .brand-name
                    - if @item.brand_id.present?
                      = @item.brand.name
                    - else
                      .no-name
            %tr
              %th 商品の状態
              %td
                .item-detail
                  = @item.condition
            %tr
              %th 配送料の負担
              %td
                .item-detail
                  = @item.shipping_fee
            %tr
              %th 配送の方法
              %td
                .item-detail らくらくメルカリ便
            %tr
              %th 発送元地域
              %td
                .item-detail.prefecture-name
                  = @item.prefecture.name
            %tr
              %th 配送日の目安
              %td
                .item-detail
                  = @item.days_to_ship

      .item-price-box
        %span.item-price
          ¥ #{@item.price}
        %span.item-tax (税込)
        %span.item-shipping-fee
          - if @item.shipping_fee=="送料込み(出品者負担)"
            送料込み
          - else
            着払い

      - unless @item.user == current_user
        - unless @item.sales_condition
          - if user_signed_in?
            = link_to "/items/#{@item.id}/buy", data: { turbolinks: false} do
              .item-buy-btn 購入画面に進む
          - else
            = link_to "/users/sign_in" do
              .item-buy-btn 購入画面に進む
        -else
          .item-buy-btn-sold 売り切れました



      .item-description
        %p.item-description__inner
          = @item.comment
      .item-button-container
        .item-button-left
          %button{type: "button", name: "like!", class: "item-button"}
            %i.far.fa-heart
            %span.fade-in-down いいね!
            %span.fade-in-down 0
          = link_to "", class: "item-button__report" do
            %i.far.fa-flag
            不適切な商品の報告
        .item-button-right
          = link_to 'https://www.mercari.com/jp/safe/description/', target: "_blank", class: "safe-description" do
            %i.fas.fa-lock.clock-font
            あんしん・あんぜんへの取り組み
    - if user_signed_in? && current_user.id == @item.user_id
      .parent-own-item-container
        - unless @item.sales_condition
          = link_to "商品の編集", edit_item_path(@item), class: "parent-own-item-container__edit"
          .parent-own-item-container__or
            or
          - unless @item.sales_condition == 0
            = link_to "出品を停止する", "#", class: "parent-own-item-container__close"
          - else
            = link_to "出品を再開する", "#", class: "parent-own-item-container__open"
        = link_to "商品を削除する", "/items/#{@item.id}", method: :delete, class: "parent-own-item-container__delete-btn"

    .item-detail-message
      .message-continer
        .message-content
          %ul.message-items
            %li.message-item
              - if @item.comment
                - @comments.each do |comment|
                  .message-user
                    %figure
                      .message-user-unknown
                        - if comment.user.user_profile.avatar.present?
                          = comment.user.user_profile.avatar
                        - else
                          = image_tag("user-icon.svg")

                    .message-body-continer
                      %p.user-name-string-nickname
                        = comment.user.user_profile.nickname
                        .message-body
                          %p
                          = comment.content
                          .message-body__text
                          .message-icons
                            .message-icon-left
                              %i.far.fa-clock
                              %span.days-ago
                                = comment.created_at.strftime("%Y/%m/%d %H:%M")
                            .message-icon-right
                              = link_to "" do
                                %i.far.fa-flag

        .message-content
          = form_for @comment, url: item_comments_path(@item), html: {class: "message-form"} do |f|
            %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
            = f.text_area :content, class: "textarea-default"
            - unless @item.sales_condition
              = f.submit "コメントする", class: "message-submit button-default"
            -else
              .message-submit.button-default.sold-button-comment 売り切れのためコメントできません
    .item-social-media-box
      .text-center
      %ul.social-media-box
        %li
          = link_to "#", target: "_blank", class: "share-btn" do
            %i.fab.fa-facebook-square
        %li
          = link_to "#", target: "_blank", class: "share-btn" do
            %i.fab.fa-twitter
        %li
          = link_to "#", target: "_blank", class: "share-btn" do
            %i.fab.fa-line
        %li
          = link_to "#", target: "_blank", class: "share-btn" do
            %i.fab.fa-pinterest
  = render "layouts/aside"
  = render "layouts/footer"

app/views/items/sold.html.haml
= render "layouts/single-header"
%section.l-signup-container
  .waiting-header
    .waiting-header__icon
      .far.fa-clock#clock-custom
    .waiting-header__title 発送をお待ちください
    .waiting__messege 出品者からの発送通知をお待ちください
.items__buy_cf__container
  .items__buy_cf__container__main
    %h2.items__buy_cf__container__main__header
      購入完了しました
    .items__buy_cf__container__main__content
      .items__buy_cf__container__main__content__inner
        .items__buy_cf__container__main__content__inner__item_image_container
          = image_tag @item.item_images[0].image.url, class: "item_photo"
        %p.items__buy_cf__container__main__content__inner__item_name
          = @item.name
          %p.items__buy_cf__container__main__content__inner__buy_form__item_price
            = "¥ " + "#{@item.price}"
            %span.items__buy_cf__container__main__content__inner__buy_form__item_price__shipping_fee
              - if @item.shipping_fee == "送料込み(出品者負担)"
                送料込み
              - else
                着払い
            .payment
              .payment_text
                支払い金額
              .payment_price
                = '¥ ' + "#{@item.price}"
      = link_to "/", id: "buy-home-button" do
        .buy-home
          トップページに戻る
    .buy_user_info
      .buy_user_info_container
        %h3
          配送先
        %address
          .buy_user_info_container_text
            = "〒#{current_user.address.postal_code}"
            %br
            = "#{current_user.address.prefecture.name} #{current_user.address.city} #{current_user.address.block} #{current_user.address.building}"
            %br
            = "#{current_user.user_profile.last_name} #{current_user.user_profile.first_name}"
= render "layouts/single-footer"
= render "layouts/sell-button"