config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: {
  sessions: 'users/sessions' ,
  registrations: 'users/registrations',
  omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get "users/sign_up/registration", to: "users/registrations#sns", as: "new_user_signup_registration"
    get "users/sign_up/sms_confirmation", to: "users/registrations#phone", as: "new_user_signup_sms_confirmation"
    get "users/sign_up/address_confirmation", to: "users/registrations#address", as: "new_user_signup_address_confirmation"
    get "users/sign_up/credit_confirmation", to: "users/registrations#credit", as: "new_user_signup_credit_confirmation"
  end

  root "items#index"
  resources :items, only: [:new, :create] do
    member do

    end
  end
  resources :user_profiles, only: [:edit,:update]
  resources :users, only: [:index]
  resources :items do
    collection do
      get :category
      get :search
      post 'pay/:id' => 'items#pay', as: 'pay'
    end
    member do
      get :buy
      get :sold
    end
  end

  resources :addresses

  resources :item_images, only: [:destroy]

  resources :item_images, only: [:update, :destroy]

  resources :categories, only: [:show]
  resources :brands, only: [:show]
  resources :users  do
    collection do
      get :logout
      get :card
      get :phone
    end
  end
  resources :users, only: [:create] do
    resources :items, only: [:show] do
      collection do
        get :onsale
        get :orderd
        get :sold
      end
    end
  end
  resources :items do
    resources :comments, only: [:create]
  end
  resources :comments
end

app/views/layouts/_aside.html.haml
.aside
  .aside__banner
    .aside__banner__inner
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .aside__banner__inner__icon
        = image_tag "mercari_icon.png"
        .aside__banner__inner__icon__app
          = link_to image_tag("app-store.svg"), "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8"
          = link_to image_tag("google-play.svg"), "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja"
    = image_tag "download_content_pc.png", class: "aside__banner__image"

app/views/layouts/_carousel.html.haml
%link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", :rel => "stylesheet", :type => "text/css"}/
%script{:src => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", :type => "text/javascript"}

app/views/layouts/_cropping-modal.html.haml
.modal#croppingModal
  .modal__overlay
    .cropper
      .cropper__body
        .cropper__body__header
          %h3 写真を切り取る
        .cropper__body__edit
          %img#canvas.cropper__body__edit__canvas
          .cropper__body__edit__slider
            #zoomSlider
        .cropper__body__button
          %button.cropper__body__button__back.btn#cropperBack キャンセル
          %button.cropper__body__button__enter.btn#cropperEnter{"data-action": controller.action_name} 完了

app/views/layouts/_footer.html.haml
.footer
  %ul.footer__navigation
    %li.footer__navigation__item
      %h2 メルカリについて
      %ul
        %li
          = link_to "会社概要（運営会社）"
        %li
          = link_to "プライバシーポリシー"
        %li
          = link_to "メルカリ利用規約"
        %li
          = link_to "有償ポイントに関する特約"
        %li
          = link_to "あんしんスマホサポート制度に関する利用特約"
        %li
          = link_to "コンプライアンスポリシー"
        %li
          = link_to "個人データの安全管理に係る基本方針"
        %li
          = link_to "特定商取引に関する表記"
        %li
          = link_to "資金決済法に基づく表示"
        %li
          = link_to "法令遵守と犯罪防止のために"
        %li
          = link_to "採用情報"
    %li.footer__navigation__item
      %h2 メルカリを見る
      %ul
        %li
          = link_to "カテゴリー一覧"
        %li
          = link_to "ブランド一覧"
        %li
          = link_to "出品地域一覧"
        %li
          = link_to "公式ブログ"  
        %li
          = link_to "公式Twitter"
        %li
          = link_to "公式Face" 
    %li.footer__navigation__item
      %h2 ヘルプ&ガイド
      %ul
        %li
          = link_to "メルカリガイド"
        %li
          = link_to "メルカリロゴ利用ガイドライン"
        %li
          = link_to "お知らせ"
        %li
          = link_to "らくらくメルカリ便とは" 
        %li
          = link_to "ゆうゆうメルカリ便とは"
        %li
          = link_to "大型らくらくメルカリ便とは" 
        %li
          = link_to "車体取引ガイド"
        %li
          = link_to "返品・返金ポリシー"
        %li
          = link_to "メルカリあんしん・あんぜん宣言！"
        %li
          = link_to "偽ブランド撲滅への取り組み"               
        %li
          = link_to "メルカリボックス"   
    %li.footer__navigation__item
      %h2 国
      %ul
        %li
          = link_to "United States"
        %li
          = link_to "United Kingdom"
        %li
          = link_to "日本"
  .footer__logo
    = image_tag "logo-white.svg"
  .footer__copyright
    %p © 2019 Mercari

app/views/layouts/_header-mypage-menu.html.haml
- if current_user.user_profile
  .mypage-menu
    .mypage-menu__image
    %figure.mypage-menu__avatar
      - if current_user.user_profile.avatar.url
        = image_tag current_user.user_profile.avatar.url
      - else
        = image_tag mage_path("member_photo_noimage.png")
      %figcaption #{current_user.user_profile.nickname}

app/views/layouts/_header.html.haml
.header
  .header__container
    .header__container__search
      = link_to image_tag("logo.svg"), root_path, class: "header__container__search__logo"
      = form_tag search_items_path, method: :get, class: "header__container__search__form" do
        = text_field_tag :keyword, "", class: "header__container__search__form__input", placeholder: "キーワードから探す"
        = button_tag type: "submit",class: "header__container__search__form__button" do
          %i.fas.fa-search
    .header__container__navigation.navigation
      .navigation__left
        .navigation__left__category
          = link_to "カテゴリーから探す"
          .navigation__left__category__menu
            = render "items/category-menu"
        .navigation__left__brand
          = link_to "ブランドから探す"
          .navigation__left__brand__menu
            = render "items/brand-menu"
      .navigation__right
        - if user_signed_in?
          .navigation__right__mypage
            - if current_user.user_profile && current_user.user_profile.avatar.url
              = image_tag current_user.user_profile.avatar.url
            - else
              = image_tag image_path("member_photo_noimage.png")
            = link_to "マイページ", users_path, class: "navigation__right__mypage__link"
          .navigation__right__note
            = link_to "お知らせ", "#"
            .navigation__right__note__list
              = render "layouts/note-list"
          .navigation__right__todo
            = link_to "やることリスト", "#"
            .navigation__right__todo__list
              = render "layouts/todo-list"
        - else
          = link_to "ログイン", new_user_session_path, class: "btn btn-nav btn-login btn-red"
          = link_to "新規会員登録", new_user_registration_path, class: "btn btn-nav btn-reg"

-# パンくず
.pankuzu
  = breadcrumbs separator: " &rsaquo; "

app/views/layouts/_note-list.html.haml
%ul.todo-list
  %li 現在、お知らせはありません

app/views/layouts/_sell-button.html.haml
.sell-button
  = link_to new_item_path, class: "button" do
    %h3.sell-button__text 出品
    %i.fas.fa-camera

app/views/layouts/_single-footer.html.haml
.single-footer
  %ul
    %li
      = link_to "プライバシーポリシー", "/"
    %li
      = link_to "メルカリ利用規約", "/"
    %li
      = link_to "特定商取引に関する表記", "/"
  = link_to image_tag("logo-gray.svg"), "/", class: "single-footer__logo"
  %p
    %small ©︎2019 Mercari

app/views/layouts/_single-header.html.haml
.single-header
  = link_to image_tag("logo.svg"), "/"

app/views/layouts/_todo-list.html.haml
%ul.todo-list
  %li 現在、やることリストはありません

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{name: "google-site-verification", content:"_OtcbthOyTMQF1lBuCfKK0RSNGb821aG312-Acs_JhY"}
    -if content_for?(:head)
      = yield(:head)
    %title FreemarketSample46a
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield